# DON'T EDIT THIS!
#
#
[package]
name = "grep-starter-rust"
version = "0.1.0"
authors = ["Youssef-Shehata"]
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytes = "1.11.1"                                  # helps manage buffers
clap = "4.5.18"
thiserror = "1.0.38"                             # error handling
