# DON'T EDIT THIS!
#
#
[package]
name = "grep-starter-rust"
version = "0.1.0"
authors = ["Youssef-Shehata"]
edition = "2021"

[dependencies]
bytes = "1.3.0"                                  # helps manage buffers
thiserror = "1.0.38"                             # error handling
